global using System.Collections.Generic;
global using System;
global using System.Linq;
global using System.Text;
global using System.IO;
global using System.Threading.Tasks;
global using System.Diagnostics;
global using System.Text.RegularExpressions;
global using System.Xml;
global using System.Xml.Linq;
global using System.Collections.Immutable;
global using System.Collections;
global using SunamoXml._sunamo.SunamoDictionary;
global using SunamoXml._sunamo.SunamoExtensions;
global using SunamoXml._sunamo.SunamoStringReplace;
global using SunamoXml._sunamo.SunamoExceptions;
global using SunamoXml._sunamo.SunamoString;
global using System.Reflection;
global using System.Net;
global using System.Diagnostics.CodeAnalysis;
global using SunamoXml;
global using SunamoXml.Generators;
global using SunamoXml._sunamo;
global using SunamoXml._sunamo.SunamoCollectionsGeneric;
global using SunamoXml._sunamo.SunamoInterfaces.Interfaces;
global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using Microsoft.Extensions.Logging;
global using NullLogger = Microsoft.Extensions.Logging.Abstractions.NullLogger;
